version: 2
updates:
  - package-ecosystem: composer
    directory: "/"
    schedule:
      interval: weekly
      day: "sunday"
      time: "02:30"
      timezone: America/Los_Angeles
    open-pull-requests-limit: 10
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: "sunday"
      time: "02:30"
      timezone: America/Los_Angeles
    open-pull-requests-limit: 10